import React from "react";
import {ReactComponent as SearchIcon} from '../icons/search.svg';
import {ReactComponent as MoonIcon} from '../icons/moon.svg';
import {ReactComponent as SunIcon} from '../icons/sun.svg';
import {ReactComponent as CloseIcon} from '../icons/close.svg';
import {ReactComponent as ArchiveIcon} from '../icons/archive.svg';
import {ReactComponent as NotesIcon} from '../icons/notes.svg';
import {ReactComponent as UnArchiveIcon} from '../icons/unarchive.svg';
import {ReactComponent as PinIcon} from '../icons/pin.svg';
import {ReactComponent as PinnedIcon} from '../icons/pinned.svg';
import {ReactComponent as ThrashIcon} from '../icons/trash.svg';
import {ReactComponent as TrashRestoreIcon} from '../icons/trashRestore.svg';

export const SEARCH_ICON = <SearchIcon />;
export const MOON_ICON = <MoonIcon />;
export const SUN_ICON = <SunIcon />;
export const CLOSE_ICON = <CloseIcon />;
export const ARCHIVE_ICON = <ArchiveIcon />;
export const NOTES_ICON = <NotesIcon />;
export const UN_ARCHIVE_ICON = <UnArchiveIcon />;
export const PIN_ICON = <PinIcon />;
export const PINNED_ICON = <PinnedIcon />;
export const THRASH_ICON = <ThrashIcon />;
export const TRASH_RESTORE_ICON = <TrashRestoreIcon />;
